# Setup
title: Ju Yeon Hong
description: portfolio
url: https://zxcvasdf99.github.io
avatar: /cat.jpeg
paginate: 5
permalink: pretty
cover_image: /galaxy.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
# twitter:
#   username: vszhub
#   card: summary
# logo: logo.png
social:
  name: ju yeon Hong
  links:
    - https://github.com/zxcvasdf99
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: ju yeon Hong
  url: https://github.com/zxcvasdf99/
  email: ghdwn643@naver.com
